/*
 * generated by Xtext 2.14.0
 */
package uk.ac.york.cs.ecss.language.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link EcssLanguageWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractEcssLanguageWebModule extends DefaultWebModule {

}
