/*
 * generated by Xtext 2.18.0
 */
package uk.ac.york.cs.ecss.examples.spacetransportationservice.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class StsLanguageFlexProposalProvider extends AbstractStsLanguageFlexProposalProvider {
}
