/*
 * generated by Xtext 2.14.0
 */
package uk.ac.york.cs.ecss.language.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEcssLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage.eINSTANCE);
		return result;
	}
}
