/*
 * generated by Xtext 2.14.0
 */
package uk.ac.york.cs.ecss.language.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEcssLanguageScopeProvider extends DelegatingScopeProvider {
}
