language: java

dist: trusty

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
#- git clone https://github.com/patrickneubauer/ECSS-DATA ~/build/patrickneubauer/ECSS-DATA
- wget https://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip
- unzip -qq apache-maven-3.5.3-bin.zip
- export M2_HOME=$PWD/apache-maven-3.5.3
- export PATH=$M2_HOME/bin:$PATH
- Xvfb :1 -screen 0 1360x1024x24 &
- export DISPLAY=:1

cache:
  directories:
  - $HOME/.m2/repository
install: /bin/true
script:
- mvn clean install -q # -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
#- mvn clean install -DskipTests
#- mvn clean install -Prun-tests

after_failure:
  - cat uk.ac.york.cs.ecss/target/surefire-reports/*.txt
