grammar opL

import "http://basic/b"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore


Window:
	'WINDOW'/* Could not find attr for [[org.eclipse.emf.ecore.impl.EAttributeImpl@30e6a763 (name: name) (ordered: true, unique: true, lowerBound: 1, upperBound: 1) (changeable: true, volatile: false, transient: false, defaultValueLiteral: null, unsettable: false, derived: false) (iD: false)]] */;

terminal ID : '^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;