/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language;

import uk.ac.york.cs.ecss.language.AbstractEcssLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EcssLanguageRuntimeModule extends AbstractEcssLanguageRuntimeModule {
}
