/*
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.examples.spacetransportationservice.ide


/**
 * Use this class to register ide components.
 */
class StsLanguageIdeModule extends AbstractStsLanguageIdeModule {
}
