/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.ide;

import uk.ac.york.cs.ecss.language.ide.AbstractEcssLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EcssLanguageIdeModule extends AbstractEcssLanguageIdeModule {
}
