/*
 * generated by Xtext 2.15.0
 */
package uk.ac.york.simpleregexp.simplereg.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import uk.ac.york.simpleregexp.simplereg.services.SimpleRegGrammarAccess;

@SuppressWarnings("all")
public class SimpleRegSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SimpleRegGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ParenthesizedRegexElement_LeftParenthesisKeyword_0_a;
	protected AbstractElementAlias match_ParenthesizedRegexElement_LeftParenthesisKeyword_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SimpleRegGrammarAccess) access;
		match_ParenthesizedRegexElement_LeftParenthesisKeyword_0_a = new TokenAlias(true, true, grammarAccess.getParenthesizedRegexElementAccess().getLeftParenthesisKeyword_0());
		match_ParenthesizedRegexElement_LeftParenthesisKeyword_0_p = new TokenAlias(true, false, grammarAccess.getParenthesizedRegexElementAccess().getLeftParenthesisKeyword_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ParenthesizedRegexElement_LeftParenthesisKeyword_0_a.equals(syntax))
				emit_ParenthesizedRegexElement_LeftParenthesisKeyword_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ParenthesizedRegexElement_LeftParenthesisKeyword_0_p.equals(syntax))
				emit_ParenthesizedRegexElement_LeftParenthesisKeyword_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '.' (rule start)
	 *     (rule start) (ambiguity) '.' cardinality='*'
	 *     (rule start) (ambiguity) '.' cardinality='+'
	 *     (rule start) (ambiguity) '.' cardinality='?'
	 *     (rule start) (ambiguity) '.' hasMinCard?='{'
	 *     (rule start) (ambiguity) value=MULTICHARTERMINAL
	 *     (rule start) (ambiguity) value=TSINGLECHARSDT
	 *     (rule start) (ambiguity) {RegexAlternatives.elements+=}
	 *     (rule start) (ambiguity) {RegexGroup.elements+=}
	 */
	protected void emit_ParenthesizedRegexElement_LeftParenthesisKeyword_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '.' ')' (rule start)
	 *     (rule start) (ambiguity) '.' cardinality='*'
	 *     (rule start) (ambiguity) '.' cardinality='+'
	 *     (rule start) (ambiguity) '.' cardinality='?'
	 *     (rule start) (ambiguity) '.' hasMinCard?='{'
	 *     (rule start) (ambiguity) value=MULTICHARTERMINAL
	 *     (rule start) (ambiguity) value=TSINGLECHARSDT
	 *     (rule start) (ambiguity) {RegexAlternatives.elements+=}
	 *     (rule start) (ambiguity) {RegexGroup.elements+=}
	 */
	protected void emit_ParenthesizedRegexElement_LeftParenthesisKeyword_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
