/*
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.examples.spacetransportationservice


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StsLanguageStandaloneSetup extends StsLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new StsLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
