/*
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.ide


/**
 * Use this class to register ide components.
 */
class EcssLanguageIdeModule extends AbstractEcssLanguageIdeModule {
}
