/**
 * generated by Xtext 2.14.0
 */
package uk.ac.york.cs.ecss.language.ecssLanguage;

import java.math.BigDecimal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#isHasMinImprovement <em>Has Min Improvement</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#getMinImprovement <em>Min Improvement</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#isHasMaxDegression <em>Has Max Degression</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#getMaxDegression <em>Max Degression</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#isHaxMaxThings <em>Hax Max Things</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#getMaxThings <em>Max Things</em>}</li>
 * </ul>
 *
 * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getConfig()
 * @model
 * @generated
 */
public interface Config extends EObject
{
  /**
   * Returns the value of the '<em><b>Has Min Improvement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Min Improvement</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Min Improvement</em>' attribute.
   * @see #setHasMinImprovement(boolean)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getConfig_HasMinImprovement()
   * @model
   * @generated
   */
  boolean isHasMinImprovement();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#isHasMinImprovement <em>Has Min Improvement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Min Improvement</em>' attribute.
   * @see #isHasMinImprovement()
   * @generated
   */
  void setHasMinImprovement(boolean value);

  /**
   * Returns the value of the '<em><b>Min Improvement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Min Improvement</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Improvement</em>' attribute.
   * @see #setMinImprovement(BigDecimal)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getConfig_MinImprovement()
   * @model
   * @generated
   */
  BigDecimal getMinImprovement();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#getMinImprovement <em>Min Improvement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Improvement</em>' attribute.
   * @see #getMinImprovement()
   * @generated
   */
  void setMinImprovement(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Has Max Degression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Max Degression</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Max Degression</em>' attribute.
   * @see #setHasMaxDegression(boolean)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getConfig_HasMaxDegression()
   * @model
   * @generated
   */
  boolean isHasMaxDegression();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#isHasMaxDegression <em>Has Max Degression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Max Degression</em>' attribute.
   * @see #isHasMaxDegression()
   * @generated
   */
  void setHasMaxDegression(boolean value);

  /**
   * Returns the value of the '<em><b>Max Degression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Degression</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Degression</em>' attribute.
   * @see #setMaxDegression(BigDecimal)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getConfig_MaxDegression()
   * @model
   * @generated
   */
  BigDecimal getMaxDegression();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#getMaxDegression <em>Max Degression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Degression</em>' attribute.
   * @see #getMaxDegression()
   * @generated
   */
  void setMaxDegression(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Hax Max Things</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hax Max Things</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hax Max Things</em>' attribute.
   * @see #setHaxMaxThings(boolean)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getConfig_HaxMaxThings()
   * @model
   * @generated
   */
  boolean isHaxMaxThings();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#isHaxMaxThings <em>Hax Max Things</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hax Max Things</em>' attribute.
   * @see #isHaxMaxThings()
   * @generated
   */
  void setHaxMaxThings(boolean value);

  /**
   * Returns the value of the '<em><b>Max Things</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Things</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Things</em>' attribute.
   * @see #setMaxThings(int)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getConfig_MaxThings()
   * @model
   * @generated
   */
  int getMaxThings();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.Config#getMaxThings <em>Max Things</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Things</em>' attribute.
   * @see #getMaxThings()
   * @generated
   */
  void setMaxThings(int value);

} // Config
