/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.ecssLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.IfExpression#getVal <em>Val</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.IfExpression#getThen <em>Then</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.IfExpression#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getIfExpression()
 * @model
 * @generated
 */
public interface IfExpression extends TemplateRulePart
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(String)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getIfExpression_Val()
   * @model
   * @generated
   */
  String getVal();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.IfExpression#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(String value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateRulePart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference list.
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getIfExpression_Then()
   * @model containment="true"
   * @generated
   */
  EList<TemplateRulePart> getThen();

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateRulePart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference list.
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getIfExpression_Else()
   * @model containment="true"
   * @generated
   */
  EList<TemplateRulePart> getElse();

} // IfExpression
