/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.ecssLanguage;

import java.math.BigDecimal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#getValue <em>Value</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#getValueNumb <em>Value Numb</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#getOclvalue <em>Oclvalue</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#isHasProperty <em>Has Property</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#getArgument <em>Argument</em>}</li>
 * </ul>
 *
 * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getPropertyValue()
 * @model
 * @generated
 */
public interface PropertyValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getPropertyValue_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Value Numb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Numb</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Numb</em>' attribute.
   * @see #setValueNumb(BigDecimal)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getPropertyValue_ValueNumb()
   * @model
   * @generated
   */
  BigDecimal getValueNumb();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#getValueNumb <em>Value Numb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Numb</em>' attribute.
   * @see #getValueNumb()
   * @generated
   */
  void setValueNumb(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Oclvalue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Oclvalue</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oclvalue</em>' containment reference.
   * @see #setOclvalue(SpecificationCS)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getPropertyValue_Oclvalue()
   * @model containment="true"
   * @generated
   */
  SpecificationCS getOclvalue();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#getOclvalue <em>Oclvalue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Oclvalue</em>' containment reference.
   * @see #getOclvalue()
   * @generated
   */
  void setOclvalue(SpecificationCS value);

  /**
   * Returns the value of the '<em><b>Has Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Property</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Property</em>' attribute.
   * @see #setHasProperty(boolean)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getPropertyValue_HasProperty()
   * @model
   * @generated
   */
  boolean isHasProperty();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue#isHasProperty <em>Has Property</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Property</em>' attribute.
   * @see #isHasProperty()
   * @generated
   */
  void setHasProperty(boolean value);

  /**
   * Returns the value of the '<em><b>Argument</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.york.cs.ecss.language.ecssLanguage.PropertyValue}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Argument</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument</em>' containment reference list.
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getPropertyValue_Argument()
   * @model containment="true"
   * @generated
   */
  EList<PropertyValue> getArgument();

} // PropertyValue
