/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.ecssLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Slot Match</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.SlotMatch#getFirst <em>First</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.SlotMatch#getSecond <em>Second</em>}</li>
 * </ul>
 *
 * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getSlotMatch()
 * @model
 * @generated
 */
public interface SlotMatch extends EObject
{
  /**
   * Returns the value of the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>First</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>First</em>' containment reference.
   * @see #setFirst(SingleSelector)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getSlotMatch_First()
   * @model containment="true"
   * @generated
   */
  SingleSelector getFirst();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.SlotMatch#getFirst <em>First</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First</em>' containment reference.
   * @see #getFirst()
   * @generated
   */
  void setFirst(SingleSelector value);

  /**
   * Returns the value of the '<em><b>Second</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Second</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second</em>' containment reference.
   * @see #setSecond(SingleSelector)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getSlotMatch_Second()
   * @model containment="true"
   * @generated
   */
  SingleSelector getSecond();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.SlotMatch#getSecond <em>Second</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second</em>' containment reference.
   * @see #getSecond()
   * @generated
   */
  void setSecond(SingleSelector value);

} // SlotMatch
