/**
 * generated by Xtext 2.14.0
 */
package uk.ac.york.cs.ecss.language.ecssLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Template Parameter Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getPropName <em>Prop Name</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getVarName <em>Var Name</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getSlotName <em>Slot Name</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getMinValue <em>Min Value</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getMaxValue <em>Max Value</em>}</li>
 *   <li>{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getDirect <em>Direct</em>}</li>
 * </ul>
 *
 * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getTemplateParameterValue()
 * @model
 * @generated
 */
public interface TemplateParameterValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Prop Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prop Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop Name</em>' attribute.
   * @see #setPropName(String)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getTemplateParameterValue_PropName()
   * @model
   * @generated
   */
  String getPropName();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getPropName <em>Prop Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prop Name</em>' attribute.
   * @see #getPropName()
   * @generated
   */
  void setPropName(String value);

  /**
   * Returns the value of the '<em><b>Var Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name</em>' attribute.
   * @see #setVarName(String)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getTemplateParameterValue_VarName()
   * @model
   * @generated
   */
  String getVarName();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getVarName <em>Var Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name</em>' attribute.
   * @see #getVarName()
   * @generated
   */
  void setVarName(String value);

  /**
   * Returns the value of the '<em><b>Slot Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Slot Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slot Name</em>' attribute.
   * @see #setSlotName(String)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getTemplateParameterValue_SlotName()
   * @model
   * @generated
   */
  String getSlotName();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getSlotName <em>Slot Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slot Name</em>' attribute.
   * @see #getSlotName()
   * @generated
   */
  void setSlotName(String value);

  /**
   * Returns the value of the '<em><b>Min Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Min Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Value</em>' attribute.
   * @see #setMinValue(int)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getTemplateParameterValue_MinValue()
   * @model
   * @generated
   */
  int getMinValue();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getMinValue <em>Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Value</em>' attribute.
   * @see #getMinValue()
   * @generated
   */
  void setMinValue(int value);

  /**
   * Returns the value of the '<em><b>Max Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Value</em>' attribute.
   * @see #setMaxValue(int)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getTemplateParameterValue_MaxValue()
   * @model
   * @generated
   */
  int getMaxValue();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getMaxValue <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Value</em>' attribute.
   * @see #getMaxValue()
   * @generated
   */
  void setMaxValue(int value);

  /**
   * Returns the value of the '<em><b>Direct</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direct</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direct</em>' attribute.
   * @see #setDirect(String)
   * @see uk.ac.york.cs.ecss.language.ecssLanguage.EcssLanguagePackage#getTemplateParameterValue_Direct()
   * @model
   * @generated
   */
  String getDirect();

  /**
   * Sets the value of the '{@link uk.ac.york.cs.ecss.language.ecssLanguage.TemplateParameterValue#getDirect <em>Direct</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direct</em>' attribute.
   * @see #getDirect()
   * @generated
   */
  void setDirect(String value);

} // TemplateParameterValue
