/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.simpleregexp.simplereg.simpleReg.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.york.simpleregexp.simplereg.simpleReg.SimpleRegPackage;
import uk.ac.york.simpleregexp.simplereg.simpleReg.Wildcard;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Wildcard</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WildcardImpl extends AbstractElementImpl implements Wildcard
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WildcardImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimpleRegPackage.Literals.WILDCARD;
  }

} //WildcardImpl
