/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.web;

import uk.ac.york.cs.ecss.language.web.AbstractEcssLanguageWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class EcssLanguageWebModule extends AbstractEcssLanguageWebModule {
}
