/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.scoping;

import uk.ac.york.cs.ecss.language.scoping.AbstractEcssLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class EcssLanguageScopeProvider extends AbstractEcssLanguageScopeProvider {
}
