/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.york.cs.ecss.language.EcssLanguageRuntimeModule;
import uk.ac.york.cs.ecss.language.EcssLanguageStandaloneSetup;
import uk.ac.york.cs.ecss.language.ide.EcssLanguageIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EcssLanguageIdeSetup extends EcssLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    EcssLanguageRuntimeModule _ecssLanguageRuntimeModule = new EcssLanguageRuntimeModule();
    EcssLanguageIdeModule _ecssLanguageIdeModule = new EcssLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_ecssLanguageRuntimeModule, _ecssLanguageIdeModule));
  }
}
