/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.simpleregexp.simplereg;

import uk.ac.york.simpleregexp.simplereg.SimpleRegStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimpleRegStandaloneSetup extends SimpleRegStandaloneSetupGenerated {
  public static void doSetup() {
    new SimpleRegStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
