grammar router.Router

import "http://www.eclipse.org/2008/Xtext" as xtext
import "http://www.eclipse.org/emf/2002/Ecore" as ep
import "http://router/1.0" as myEcore

CopperCable returns myEcore::CopperCable:
	{myEcore::CopperCable} "CopperCable" name=ID "{" (("source" source=[myEcore::Device]) ("speed" speed=STRING)
	("target" target=[myEcore::Device])) "}";

Router returns myEcore::Router:
	{myEcore::Router} "Router" name=ID "{" (("incoming" incoming+=[myEcore::Cable]*) ("maxSpeed" maxSpeed=STRING)
	("outgoing" outgoing+=Cable*)) "}";

GlassFiberCable returns myEcore::GlassFiberCable:
	{myEcore::GlassFiberCable} "GlassFiberCable" name=ID "{" (("source" source=[myEcore::Device]) ("speed" speed=STRING)
	("target" target=[myEcore::Device])) "}";

Device returns myEcore::Device:
	{myEcore::Device} (Server | Computer | Router);

Agent returns myEcore::Agent:
	{myEcore::Agent} (Provider | Consumer);

Consumer returns myEcore::Consumer:
	{myEcore::Consumer} "Consumer" name=ID "{" (("rightcomp" rightcomp=[myEcore::Computer]) ("speed" speed=STRING)) "}";

Computer returns myEcore::Computer:
	{myEcore::Computer} "Computer" name=ID "{" (("consumer" consumer=[myEcore::Consumer]) ("incoming"
	incoming+=[myEcore::Cable]*) ("outgoing" outgoing+=Cable*)) "}";

Provider returns myEcore::Provider:
	{myEcore::Provider} "Provider" name=ID "{" (("rightserv" rightserv=[myEcore::Server]) ("speed" speed=STRING)) "}";

Cable returns myEcore::Cable:
	{myEcore::Cable} (CopperCable | GlassFiberCable);

Container returns myEcore::Container:
	{myEcore::Container} "Container" "{" (("agents" agents+=Agent*) ("devices" devices+=Device*)) "}";

Server returns myEcore::Server:
	{myEcore::Server} "Server" name=ID "{" (("incoming" incoming+=[myEcore::Cable]*) ("outgoing" outgoing+=Cable*)
	("provider" provider=[myEcore::Provider]?)) "}";

terminal ID:
	("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;

terminal INT:
	"0".."9";

terminal STRING:
	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
