/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.simpleregexp.simplereg.simpleReg.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test suite for the '<em><b>simpleReg</b></em>' package.
 * <!-- end-user-doc -->
 * @generated
 */
public class SimpleRegTests extends TestSuite {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(suite());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static Test suite() {
		TestSuite suite = new SimpleRegTests("simpleReg Tests");
		return suite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SimpleRegTests(String name) {
		super(name);
	}

} //SimpleRegTests
