/*
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class EcssLanguageWebModule extends AbstractEcssLanguageWebModule {
}
