/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.simpleregexp.simplereg.simpleReg;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regex Alternatives</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.york.simpleregexp.simplereg.simpleReg.RegexAlternatives#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see uk.ac.york.simpleregexp.simplereg.simpleReg.SimpleRegPackage#getRegexAlternatives()
 * @model
 * @generated
 */
public interface RegexAlternatives extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.york.simpleregexp.simplereg.simpleReg.AbstractElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see uk.ac.york.simpleregexp.simplereg.simpleReg.SimpleRegPackage#getRegexAlternatives_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractElement> getElements();

} // RegexAlternatives
