/*
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.simpleregexp.simplereg.ide


/**
 * Use this class to register ide components.
 */
class SimpleRegIdeModule extends AbstractSimpleRegIdeModule {
}
