/**
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.ui.contentassist;

import uk.ac.york.cs.ecss.language.ui.contentassist.AbstractEcssLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EcssLanguageProposalProvider extends AbstractEcssLanguageProposalProvider {
}
