/*
 * generated by Xtext 2.15.0
 */
package uk.ac.york.cs.ecss.language.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.york.cs.ecss.language.ui.internal.LanguageActivator;

public class EcssLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LanguageActivator.getInstance().getInjector("uk.ac.york.cs.ecss.language.EcssLanguage");
	}

}
